services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_opendatalens
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: opendatalens
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: securepassword
    volumes:
      - mongodb_data:/data/db
      - ./database/initdb.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
  mongodb_data: